// Generated by scripts/generate_contracts.py; do not edit.
export type Annotation = { "id": string; "subject_id": string; "subject_unit": "asset" | "example" | "entity" | "conversation"; "namespace"?: "source" | "prediction" | "human"; "field_id": string; "value"?: unknown; "provenance"?: { [key: string]: unknown }; "annotator"?: string | null; "aggregation"?: string | null };

export type Artifact = { "schema_version"?: string; "id": string; "kind": string; "run_id"?: string | null; "snapshot_ids": (string)[]; "unit": "asset" | "example" | "entity" | "conversation"; "ids": (string)[]; "files"?: { [key: string]: string }; "provenance"?: { [key: string]: unknown }; "coverage"?: { [key: string]: unknown }; "data"?: { [key: string]: unknown } };

export type Asset = { "id": string; "dataset_id": string; "release_id": string; "modality": string; "uri"?: string | null; "text"?: string | null; "representation"?: string; "sha256"?: string | null; "metadata"?: { [key: string]: unknown } };

export type Availability = { "preview"?: "local" | "on_request" | "none"; "complete_data"?: "local" | "on_request" | "none"; "upstream_preview_count"?: number };

export type Capabilities = { "schema_version"?: string; "mode": "static" | "workbench"; "operations": (string)[]; "api_version"?: string; "limits"?: { [key: string]: number } };

export type Coverage = { "identity"?: string; "source"?: string; "access"?: string; "adapter"?: string; "preview"?: string; "complete_data"?: string; "publication"?: string; "preview_count"?: number; "total_count"?: number | null; "unit"?: "asset" | "example" | "entity" | "conversation"; "blockers"?: (string)[] };

export type Dataset = { "schema_version"?: string; "id": string; "name": string; "origin"?: "catalogue" | "user"; "aliases"?: (string)[]; "description"?: string; "tasks"?: (string)[]; "modalities"?: (string)[]; "labels"?: (string)[]; "paper_ids"?: (string)[]; "source_url"?: string | null; "release"?: string; "snapshot_id"?: string; "adapter"?: string; "adapter_config"?: { [key: string]: unknown }; "coverage"?: Coverage; "availability"?: Availability | null; "rights"?: { [key: string]: string }; "relationships"?: ({ [key: string]: unknown })[]; "evidence"?: ({ [key: string]: unknown })[] };

export type Entity = { "id": string; "asset_id": string; "dataset_id": string; "release_id": string; "geometry"?: { [key: string]: unknown }; "coordinate_system"?: string; "provenance"?: { [key: string]: unknown } };

export type FieldDescriptor = { "id": string; "name": string; "dtype"?: "string" | "number" | "boolean" | "category" | "array" | "object"; "namespace"?: "source" | "prediction" | "human" | "record"; "values"?: (unknown)[] | null; "unit"?: "asset" | "example" | "entity" | "conversation"; "description"?: string; "provenance"?: { [key: string]: unknown }; "query_ops"?: (string)[] };

export type Measurement = { "value": number; "unit": string; "scope": "reported_upstream" | "reported_in_paper" | "complete_available_release" | "preview" | "filtered_selection"; "release_id": string; "split"?: string | null; "selection_id"?: string | null; "source": { [key: string]: unknown }; "method": string };

export type Pack = { "schema_version"?: string; "dataset": Dataset; "fields": (FieldDescriptor)[]; "records": (Record)[]; "artifacts"?: (Artifact)[]; "population_scope"?: string; "sampling"?: { [key: string]: unknown }; "checksums"?: { [key: string]: string } };

export type Query = { "population_scope"?: "preview" | "complete"; "result_snapshot_ids"?: (string)[]; "snapshot_id": string; "unit"?: "asset" | "example" | "entity" | "conversation"; "filter"?: { [key: string]: unknown } | null; "search"?: string; "sort"?: ({ [key: string]: string })[]; "limit"?: number; "cursor"?: string | null; "sample"?: { [key: string]: unknown } | null };

export type QueryResult = { "snapshot_id": string; "unit": "asset" | "example" | "entity" | "conversation"; "population_scope": string; "records": (Record)[]; "returned_count": number; "matched_count": number | null; "count_status"?: "exact" | "estimated" | "unknown"; "coverage"?: { [key: string]: unknown }; "ordering"?: ({ [key: string]: string })[]; "cursor"?: string | null; "warnings"?: (string)[] };

export type Record = { "schema_version"?: string; "id": string; "dataset_id": string; "release_id": string; "snapshot_id": string; "unit"?: "asset" | "example" | "entity" | "conversation"; "asset_ids"?: (string)[]; "assets"?: (Asset)[]; "text"?: string | null; "question"?: string | null; "choices"?: (unknown)[]; "conversation"?: ({ [key: string]: unknown })[]; "source"?: { [key: string]: unknown }; "prediction"?: { [key: string]: unknown }; "human"?: { [key: string]: unknown }; "annotations"?: (Annotation)[]; "relations"?: (Relation)[] };

export type Relation = { "subject_id": string; "object_id": string; "type": string; "provenance"?: { [key: string]: unknown } };

export type Release = { "schema_version"?: string; "id": string; "dataset_id": string; "revision": string; "snapshot_id": string; "source"?: { [key: string]: unknown }; "measurements"?: ({ [key: string]: unknown })[] };

export type Run = { "schema_version"?: string; "id": string; "processor_id": string; "selection_id": string; "status"?: string; "config"?: { [key: string]: unknown }; "provenance"?: { [key: string]: unknown }; "progress"?: { [key: string]: unknown }; "errors"?: ({ [key: string]: unknown })[]; "artifact_ids"?: (string)[]; "created_at": string; "completed_at"?: string | null };

export type Selection = { "schema_version"?: string; "id": string; "name"?: string; "ids": (string)[]; "unit": "asset" | "example" | "entity" | "conversation"; "snapshot_ids": (string)[]; "dataset_ids": (string)[]; "method"?: string; "seed"?: number | null; "query"?: { [key: string]: unknown }; "created_at": string };
