"""Generate JSON Schema and TS types from the Pydantic source of truth."""
import json
from pathlib import Path
from dataset_atlas import models

ROOT = Path(__file__).resolve().parents[1]
classes = [getattr(models, name) for name in ['Dataset','Release','Asset','Entity','Measurement','Annotation','Relation','Record','FieldDescriptor','Query','QueryResult','Selection','Run','Artifact','Capabilities','Pack']]
def ts(s):
    if isinstance(s, bool): return 'unknown'
    if '$ref' in s: return s['$ref'].split('/')[-1]
    if 'anyOf' in s: return ' | '.join(ts(v) for v in s['anyOf'])
    if 'enum' in s: return ' | '.join(json.dumps(v) for v in s['enum'])
    if 'const' in s: return json.dumps(s['const'])
    t=s.get('type')
    if t=='array': return '('+ts(s.get('items',{}))+')[]'
    if t=='object':
        if 'properties' in s:
            required=s.get('required',[])
            return '{ '+ '; '.join(json.dumps(k)+('' if k in required else '?')+': '+ts(v) for k,v in s['properties'].items())+' }'
        return '{ [key: string]: '+ts(s.get('additionalProperties',{}))+' }'
    return {'string':'string','integer':'number','number':'number','boolean':'boolean','null':'null'}.get(t,'unknown')

def generate():
    definitions={}
    for cls in classes:
        schema=cls.model_json_schema(mode='serialization')
        definitions.update(schema.pop('$defs',{}))
        definitions[cls.__name__]=schema
    root={'$schema':'https://json-schema.org/draft/2020-12/schema','$defs':definitions}
    (ROOT/'schemas/atlas.schema.json').write_text(json.dumps(root,indent=2)+'\n')
    dest=ROOT/'apps/web/src/generated.ts';dest.parent.mkdir(parents=True,exist_ok=True)
    dest.write_text('// Generated by scripts/generate_contracts.py; do not edit.\n'+ '\n\n'.join('export type '+name+' = '+ts(s)+';' for name,s in sorted(definitions.items()))+'\n')
if __name__=='__main__': generate()
