"""Check the SPEC 22.1 acceptance-traceability matrix and optionally run its pytest nodes.

Usage: python scripts/verify_acceptance_matrix.py [--run] [--matrix FILE] [--out FILE]

Without --run the named nodes, Playwright specs and receipts are only checked to exist.
--run executes every named pytest node (never the Playwright specs) and writes the
markdown report. A passing automated check is not human acceptance.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
STATUSES = {"gap", "not_applicable"}
OUTCOME = re.compile(r"^(\S.*?) (PASSED|FAILED|ERROR|SKIPPED|XFAIL|XPASS)(?: |$)")


def _pytest(root: Path, *args: str) -> subprocess.CompletedProcess:
    env = {**os.environ, "PYTHONPATH": f"{root / 'src'}{os.pathsep}{os.environ.get('PYTHONPATH', '')}".rstrip(os.pathsep)}
    return subprocess.run([sys.executable, "-m", "pytest", "-p", "no:cacheprovider", *args], cwd=root, env=env, capture_output=True, text=True)


def collect_nodes(root: Path = ROOT) -> set[str]:
    result = _pytest(root, "--collect-only", "-q", "tests")
    nodes = {line.strip() for line in result.stdout.splitlines() if "::" in line and not line.startswith((" ", "="))}
    if not nodes:
        raise RuntimeError(f"pytest collection returned no nodes:\n{result.stdout[-2000:]}{result.stderr[-2000:]}")
    return nodes


def verify(matrix: dict, collected: set[str], root: Path = ROOT) -> list[str]:
    problems: list[str] = []
    seen: set[str] = set()
    for row in matrix.get("rows", []):
        name = row.get("id", "?")
        if name in seen:
            problems.append(f"{name}: duplicate row id")
        seen.add(name)
        status = row.get("status")
        if status is not None and status not in STATUSES:
            problems.append(f"{name}: unknown status {status!r}")
        for node in row.get("pytest", []):
            if node not in collected:
                problems.append(f"{name}: pytest node does not exist: {node}")
        for path in [*row.get("playwright", []), *row.get("receipts", [])]:
            if not (root / path).is_file():
                problems.append(f"{name}: file does not exist: {path}")
        for clause in row.get("not_applicable_clauses", []):
            if "SPEC" not in clause.get("cite", "") or not clause.get("clause"):
                problems.append(f"{name}: a not_applicable clause must name the clause and cite the SPEC")
            for node in clause.get("pytest", []):
                if node not in collected:
                    problems.append(f"{name}: pytest node does not exist: {node}")
        if status in STATUSES:
            if not row.get("note"):
                problems.append(f"{name}: {status} row needs a note")
            if status == "not_applicable" and "SPEC" not in row.get("note", ""):
                problems.append(f"{name}: not_applicable row must cite the SPEC")
        elif not (row.get("pytest") or row.get("playwright") or row.get("receipts")):
            problems.append(f"{name}: row has no test and no receipt")
    return problems


def all_nodes(matrix: dict) -> set[str]:
    return {node for row in matrix["rows"] for node in [*row.get("pytest", []), *(n for clause in row.get("not_applicable_clauses", []) for n in clause.get("pytest", []))]}


def run_nodes(nodes: list[str], root: Path = ROOT) -> dict[str, str]:
    outcomes: dict[str, str] = {}
    if nodes:
        result = _pytest(root, "-v", "--no-header", "-p", "no:randomly", *nodes)
        for line in result.stdout.splitlines():
            if match := OUTCOME.match(line):
                outcomes[match.group(1)] = match.group(2)
    return {node: outcomes.get(node, "NOT_RUN") for node in nodes}


def row_result(row: dict, outcomes: dict[str, str]) -> str:
    if row.get("status") in STATUSES:
        return row["status"]
    nodes = [*row.get("pytest", []), *(node for clause in row.get("not_applicable_clauses", []) for node in clause.get("pytest", []))]
    if any(outcomes.get(node, "NOT_RUN") != "PASSED" for node in nodes):
        return "fail"
    return "pass" if row.get("pytest") else "receipt_only"


def render(matrix: dict, outcomes: dict[str, str]) -> str:
    lines = ["# SPEC 22.1 acceptance traceability", "",
             "Generated by `scripts/verify_acceptance_matrix.py --run` from `docs/acceptance-matrix.json`.",
             "`pass` means every named pytest node passed in that run: an automated check passes. It is not human acceptance, and",
             "Playwright specs are only checked to exist (they are run by the browser suite, not here).",
             "`receipt_only` rows cite committed receipts that were not re-run. `not_applicable` and `gap` are explicit.", "",
             "| Area | Result | pytest nodes | Playwright specs | Receipts |", "| --- | --- | --- | --- | --- |"]
    details = []
    for row in matrix["rows"]:
        result = row_result(row, outcomes)
        nodes = row.get("pytest", [])
        passed = sum(outcomes.get(node) == "PASSED" for node in nodes)
        label = result + (f" (+{len(row['not_applicable_clauses'])} clause not_applicable)" if row.get("not_applicable_clauses") else "")
        lines.append(f"| {row['spec_row']} | {label} | {passed}/{len(nodes)} | {len(row.get('playwright', []))} | {len(row.get('receipts', []))} |")
        details += [f"### {row['spec_row']} ({label})", "", f"Condition: {row['condition']}", "", f"Note: {row['note']}", ""]
        details += [f"- `{node}`: {outcomes.get(node, 'NOT_RUN')}" for node in nodes]
        for clause in row.get("not_applicable_clauses", []):
            details += [f"- not_applicable clause: {clause['clause']} ({clause['cite']})"]
            details += [f"  - `{node}`: {outcomes.get(node, 'NOT_RUN')}" for node in clause.get("pytest", [])]
        details += [f"- playwright: `{path}`" for path in row.get("playwright", [])]
        details += [f"- receipt: `{path}`" for path in row.get("receipts", [])]
        details.append("")
    counts: dict[str, int] = {}
    for row in matrix["rows"]:
        counts[row_result(row, outcomes)] = counts.get(row_result(row, outcomes), 0) + 1
    summary = ", ".join(f"{count} {name}" for name, count in sorted(counts.items()))
    return "\n".join([*lines, "", f"Rows: {summary}.", "", *details]).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", action="store_true", help="execute every named pytest node and write the report")
    parser.add_argument("--matrix", type=Path, default=ROOT / "docs/acceptance-matrix.json")
    parser.add_argument("--out", type=Path, default=ROOT / "reports/acceptance_matrix.md")
    args = parser.parse_args(argv)
    matrix = json.loads(args.matrix.read_text())
    problems = verify(matrix, collect_nodes(ROOT))
    outcomes: dict[str, str] = {}
    if args.run and not problems:
        nodes = sorted(all_nodes(matrix))
        outcomes = run_nodes(nodes)
    elif args.run:
        outcomes = {node: "NOT_RUN" for node in all_nodes(matrix)}
    if args.run:
        args.out.write_text(render(matrix, outcomes))
        problems += [f"{row['id']}: automated run did not pass" for row in matrix["rows"] if row_result(row, outcomes) == "fail"]
    for problem in problems:
        print(problem, file=sys.stderr)
    gaps = [row["id"] for row in matrix["rows"] if row.get("status") == "gap"]
    print(f"{len(matrix['rows'])} rows, {len(problems)} problems, {len(gaps)} recorded gaps{': ' + ', '.join(gaps) if gaps else ''}")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
